[package]
name = "method"
version = "0.1.0"
edition = "2021"


[dependencies]
risc0-zkvm = { version = "2.0.1", default-features = false, features = ['std'] }
lib = { workspace = true, features = ['risczero'] }
